name: Ensure Version Bump
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          [[ $(git show main:pyproject.toml | grep version) == $(cat pyproject.toml | grep version) ]]
