name: Ensure Version Bump
on: [push, pull_request]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          [[
            "$(git branch --show-current)" == "main" ||
            "$(git show origin/main:pyproject.toml | grep version)" != "$(cat pyproject.toml | grep version)"
          ]]
