name: Ensure Version Bump
on: [push, pull_request]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [ "$(git branch --show-current)" == "main" ]; then
            echo "Skipping version check on main branch"
            exit 1
          fi

          if [ "$(git show main:pyproject.toml | grep version)" != "$(cat pyproject.toml | grep version)" ]; then
            echo "Version was bumped"
            exit 1
          fi

          echo "Version was not bumped"
          exit 0
