name: Ensure Version Bump
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [[ 
            $(git rev-parse --abbrev-ref HEAD) != main &&
            $(git show main:pyproject.toml | grep version) != $(cat pyproject.toml | grep version)
          ]]; then
            echo "Version bump required"
            exit 1
          fi
