name: Pytest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Pytest
        env:
          PYNPUT_BACKEND: dummy
        run: uv run pytest
